spring.application.name=MealCraft
spring.profiles.active=dev

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.output.ansi.enabled=always

# ????? ???? ??????? ?? validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???????? ??? ????????
mealcraft.recipes.external.enabled=true
mealcraft.recipes.external.url=https://www.themealdb.com/api/json/v1/1/random.php

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=mySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm123456789
jwt.cookie-name=mealcraft-token
jwt.expiration-ms=86400000
# 1 day in milliseconds

shopping-item-cleanup-tick-delay-minutes=1

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=291a5ebbb4be66
spring.mail.password=5b9afc963b5ea9

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.default-encoding=UTF-8
spring.mail.from=no-reply@mealcraft.org

# spring modulith configuration for explicitly annotated modules
spring.modulith.detection-strategy=explicitly-annotated
